### ISSUE TITLE
Detection of systemd fails in install.sh

### ISSUE THREAD

**Issue by newmedicine** [arno-iptables-firewall/aif#32] opened 2016-12-25 23:34 UTC
I'm running Raspbian Jessie with systemd on board, and I noticed that install.sh fails to install arno-iptables-firewall.service into /etc/systemd/system. 

Shouldn't
`# Install service file if systemd directory is available
if [ -d "/usr/lib/systemd/system/" ]; then
  copy_ask_if_exist ./lib/systemd/system/arno-iptables-firewall.service /usr/lib/systemd/system/
fi`
be
`# Install service file if systemd directory is available
if [ -d "/etc/systemd/system/" ]; then
  copy_ask_if_exist ./lib/systemd/system/arno-iptables-firewall.service /etc/systemd/system/
fi`
(at least for Raspbian)

Thanks, otherwise works marvellously. A way out of CSF...

Nick

**Comment by abelbeck** [comment] 2016-12-26 00:10
Thanks Nick, It would seem systemd unit files can be seen in ```/usr/lib/systemd/system/``` and ```/etc/systemd/system/``` (the latter takes precedence).

So the existence of either directory should be tested for ```arno-iptables-firewall.service``` installation.  The question, which order ?

**Comment by newmedicine** [comment] 2016-12-26 10:51
Thanks, I presume `/etc/systemd/system` first if it takes precedence? I only have experience with Debian Jessie + derivatives.

**Comment by arnova** [comment] 2016-12-28 16:50
According to the docs both should work but /etc/ takes precedence. The docs also state that packages should install in /usr/lib and only manual (admin) overwrites should go in /etc.

@newmedicine : Did it actually fail to work for you then with /usr/lib?

**Comment by newmedicine** [comment] 2016-12-29 07:53
Yes it did fail - latest Raspbian Jessie.

**Comment by arnova** [comment] 2016-12-29 08:59
@newmedicine : Fail in what way? I assume it didn't start but was there e.g. any error message?

**Comment by arnova** [comment] 2016-12-29 09:00
@newmedicine : Could it be that /usr/lib is readonly mounted on Raspbian? Did the install script generate any error?

**Comment by newmedicine** [comment] 2016-12-29 18:50
No it's not mounted ro. I'm really sorry - but I decided to keep things simple and use my home router to do the forwarding, and tidy up with rinetd doing a little bit of forwarding. I no longer have access to the logs.

Copying the .service file from /usr/lib/systemd/system/ to /etc/systemd/system/ fixed the problem (of course).

**Comment by arnova** [comment] 2017-07-10 12:10
If anyone else experiences this problem, please reopen with more info on how to reproduce. Closing for now.

**Closed by arnova** 2017-07-10 12:10 UTC

**Comment by arnova** [comment] 2017-10-24 13:41
@newmedicine : This caused also caused problems on Debian 9, as it turns out. I've committed a fix for this in master. thanks for your patience.
